r"""
maintenance.py — PC maintenance utilities for WinDesktopMgr (Maintenance tab).

Tier 1: junk / temp cleanup. Scan is read-only and always runs first so the UI
can preview exactly what will be removed and how much space it frees; cleaning
only ever touches the whitelisted category roots below — the API takes category
KEYS, never caller-supplied paths, so there is no path-traversal surface.

Design choices (carried over from the drive-swap review):
  * Preview-first: `scan_junk()` reports count/bytes/samples per category with
    no side effects; `clean_junk(keys)` acts only on those keys.
  * Safe-by-default: only USER-SCOPE junk that needs no elevation is deleted
    here (temp, caches, crash dumps, WER, Recycle Bin — all regenerated by
    Windows/apps). SYSTEM-SCOPE junk (C:\Windows\Temp, Windows Update payloads)
    is deliberately NOT deleted by this process; the tab hands those off to
    Windows' own Disk Cleanup (cleanmgr), which elevates through Windows itself
    — so the app never runs an elevated file-deleter of its own.
  * Python-first: os.scandir / os.remove / shutil.rmtree, with a ctypes
    SHFileOperation for the Recycle-Bin option and SHQuery/EmptyRecycleBin for
    the bin itself. No PowerShell.
"""

from __future__ import annotations

import ctypes
import os
import shutil
import time
from ctypes import wintypes

from flask import Blueprint, jsonify, request

maintenance_bp = Blueprint("maintenance", __name__)


# ── Junk categories ───────────────────────────────────────────────────────────
# Each category resolves to one or more ROOT directories (env-expanded at call
# time). `min_age_days` skips very recent entries so we never fight an active
# installer's temp files. `recurse` walks subdirs. Everything here is user-scope
# and regenerated on demand, so `risk` is "safe" (permanent delete); the
# `to_recycle_bin` path exists for future higher-risk categories.


def _expand(path: str) -> str:
    return os.path.expandvars(path)


def _junk_categories() -> list[dict]:
    """Return the junk categories with their roots resolved for this user.

    Kept as a function (not a module constant) so it re-reads env vars and so
    tests can monkeypatch env / the roots cleanly.
    """
    local = _expand(r"%LOCALAPPDATA%")
    return [
        {
            "key": "user_temp",
            "label": "Temporary files (your account)",
            "description": "Files left in your %TEMP% folder by installers and apps. Windows recreates it as needed.",
            "roots": [_expand(r"%TEMP%"), _expand(r"%TMP%")],
            "min_age_days": 1,  # leave today's temp alone (may be in use)
            "recurse": True,
            "risk": "safe",
        },
        {
            "key": "thumbnail_cache",
            "label": "Thumbnail & icon cache",
            "description": "Explorer's cached thumbnails/icons. Rebuilt automatically the next time you browse folders.",
            "roots": [os.path.join(local, r"Microsoft\Windows\Explorer")],
            "patterns": ("thumbcache_", "iconcache_"),
            "min_age_days": 0,
            "recurse": False,
            "risk": "safe",
        },
        {
            "key": "crash_dumps",
            "label": "Crash dumps",
            "description": "Application crash dumps in your profile. Only useful for debugging a specific crash.",
            "roots": [os.path.join(local, "CrashDumps")],
            "min_age_days": 0,
            "recurse": True,
            "risk": "safe",
        },
        {
            "key": "wer",
            "label": "Windows Error Reporting queue",
            "description": "Queued/archived error reports in your profile. Safe to clear.",
            "roots": [
                os.path.join(local, r"Microsoft\Windows\WER\ReportQueue"),
                os.path.join(local, r"Microsoft\Windows\WER\ReportArchive"),
            ],
            "min_age_days": 0,
            "recurse": True,
            "risk": "safe",
        },
        {
            "key": "recycle_bin",
            "label": "Recycle Bin",
            "description": "Everything currently in the Recycle Bin, for all drives. This is permanent — off by default.",
            "special": "recycle_bin",
            "risk": "safe",
            "default_off": True,  # emptying the bin is irreversible; don't pre-check it
        },
    ]


# ── Scanning (read-only) ──────────────────────────────────────────────────────


def _matches(name: str, patterns: tuple[str, ...] | None) -> bool:
    if not patterns:
        return True
    low = name.lower()
    return any(low.startswith(p.lower()) for p in patterns)


def _is_reparse(entry: os.DirEntry) -> bool:
    """True if a DirEntry is a symlink OR a junction/mount-point (reparse point).

    os.path.islink is False for directory junctions, so we check both — we never
    traverse INTO or delete THROUGH a reparse point (a junction planted in %TEMP%
    pointing at Documents must never be followed)."""
    try:
        if entry.is_symlink():
            return True
        is_junction = getattr(entry, "is_junction", None)
        if callable(is_junction) and is_junction():
            return True
    except OSError:
        return True  # can't tell -> treat as reparse; do not follow/delete
    return False


def _tree_has_recent(path: str, cutoff: float) -> bool:
    """True if any file under ``path`` has mtime newer than ``cutoff``.

    Lets a min-age category skip a whole directory that was created long ago but
    still holds fresh files (an active installer's temp dir): writing to an
    existing file does NOT bump the parent dir's mtime, so a top-level age check
    alone would delete live data. Short-circuits; never follows reparse points."""
    try:
        for entry in os.scandir(path):
            try:
                if entry.is_file(follow_symlinks=False):
                    if entry.stat(follow_symlinks=False).st_mtime > cutoff:
                        return True
                elif (
                    entry.is_dir(follow_symlinks=False)
                    and not _is_reparse(entry)
                    and _tree_has_recent(entry.path, cutoff)
                ):
                    return True
            except OSError:
                continue
    except OSError:
        return False
    return False


def _within_profile(root: str) -> bool:
    """Defence-in-depth: a cleanup root must be an absolute path UNDER the user
    profile. Rejects a drive root or a relative path from a misconfigured env
    var (e.g. %TEMP%=C:\\, or an empty %LOCALAPPDATA% yielding a relative root),
    so cleanup can never iterate the drive root or somewhere outside the profile.
    Every Tier-1 category lives under %USERPROFILE%."""
    if not root or not os.path.isabs(root):
        return False
    prof = os.path.expandvars("%USERPROFILE%")
    if not prof or not os.path.isabs(prof):
        return False
    n = os.path.normcase(os.path.normpath(root))
    if len(n.rstrip("\\/")) <= 2:  # drive root like "C:"
        return False
    p = os.path.normcase(os.path.normpath(prof))
    return n == p or n.startswith(p + os.sep)


def _resolved_roots(cat: dict) -> list[str]:
    """Category roots, de-duplicated (case-insensitive) and confined to the
    profile. %TEMP% and %TMP% usually resolve to the same dir; without de-dup the
    scan preview would double-count."""
    seen: set[str] = set()
    out: list[str] = []
    for root in cat.get("roots", []):
        if not _within_profile(root):
            continue
        key = os.path.normcase(os.path.normpath(root))
        if key in seen:
            continue
        seen.add(key)
        out.append(root)
    return out


def _scan_dir(root: str, *, min_age_days: int = 0, recurse: bool = True, patterns=None) -> tuple[int, int, list[str]]:
    """Return (file_count, total_bytes, sample_paths) under ``root``.

    Read-only. Silently skips entries it can't stat (locked/permission) and never
    follows reparse points. Only counts top-level entries matching ``patterns``.
    ``min_age_days`` skips entries modified within that window; for a directory it
    also skips the whole tree if it holds any file newer than the cutoff."""
    count = 0
    total = 0
    samples: list[str] = []
    cutoff = time.time() - (min_age_days * 86400) if min_age_days else None
    if not root or not os.path.isdir(root):
        return (0, 0, [])
    try:
        entries = list(os.scandir(root))
    except OSError:
        return (0, 0, [])
    for entry in entries:
        try:
            if not _matches(entry.name, patterns):
                continue
            if entry.is_file(follow_symlinks=False):
                if cutoff is not None and entry.stat(follow_symlinks=False).st_mtime > cutoff:
                    continue
                count += 1
                total += entry.stat(follow_symlinks=False).st_size
            elif entry.is_dir(follow_symlinks=False) and recurse:
                if _is_reparse(entry):
                    continue  # never traverse a junction/symlink
                if cutoff is not None and (
                    entry.stat(follow_symlinks=False).st_mtime > cutoff or _tree_has_recent(entry.path, cutoff)
                ):
                    continue  # dir holds fresh files — leave it alone
                c, b, _ = _scan_dir(entry.path, min_age_days=0, recurse=True, patterns=None)
                count += c + 1
                total += b
            else:
                continue
            if len(samples) < 5:
                samples.append(entry.path)
        except OSError:
            continue
    return (count, total, samples)


def _recycle_bin_info() -> tuple[int, int]:
    """(item_count, total_bytes) across all drives via SHQueryRecycleBinW."""

    class SHQUERYRBINFO(ctypes.Structure):
        _fields_ = [("cbSize", wintypes.DWORD), ("i64Size", ctypes.c_int64), ("i64NumItems", ctypes.c_int64)]

    info = SHQUERYRBINFO()
    info.cbSize = ctypes.sizeof(info)
    try:
        # NULL path = all drives. S_OK == 0.
        rc = ctypes.windll.shell32.SHQueryRecycleBinW(None, ctypes.byref(info))
    except Exception:  # noqa: BLE001 -- shell32 unavailable / non-Windows
        return (0, 0)
    if rc != 0:
        return (0, 0)
    return (int(info.i64NumItems), int(info.i64Size))


def _human(nbytes: int) -> str:
    n = float(nbytes)
    for unit in ("B", "KB", "MB", "GB", "TB"):
        if n < 1024 or unit == "TB":
            return f"{n:.0f} {unit}" if unit == "B" else f"{n:.1f} {unit}"
        n /= 1024
    return f"{nbytes} B"


def scan_junk() -> dict:
    """Read-only preview of removable junk. Never deletes anything."""
    cats = []
    total = 0
    for c in _junk_categories():
        if c.get("special") == "recycle_bin":
            count, nbytes = _recycle_bin_info()
            samples: list[str] = []
        else:
            count = 0
            nbytes = 0
            samples = []
            for root in _resolved_roots(c):
                rc, rb, rs = _scan_dir(
                    root,
                    min_age_days=c.get("min_age_days", 0),
                    recurse=c.get("recurse", True),
                    patterns=c.get("patterns"),
                )
                count += rc
                nbytes += rb
                samples.extend(rs)
        total += nbytes
        cats.append(
            {
                "key": c["key"],
                "label": c["label"],
                "description": c["description"],
                "risk": c.get("risk", "safe"),
                "default_off": bool(c.get("default_off")),
                "count": count,
                "bytes": nbytes,
                "human": _human(nbytes),
                "samples": samples[:5],
            }
        )
    return {"ok": True, "categories": cats, "total_bytes": total, "total_human": _human(total)}


# ── Cleaning ──────────────────────────────────────────────────────────────────

_FO_DELETE = 0x0003
_FOF_ALLOWUNDO = 0x0040
_FOF_NOCONFIRMATION = 0x0010
_FOF_SILENT = 0x0004
_FOF_NOERRORUI = 0x0400


def _send_to_recycle_bin(path: str) -> bool:
    """Delete ``path`` to the Recycle Bin via SHFileOperationW. Returns success."""

    class SHFILEOPSTRUCTW(ctypes.Structure):
        _fields_ = [
            ("hwnd", wintypes.HWND),
            ("wFunc", wintypes.UINT),
            ("pFrom", wintypes.LPCWSTR),
            ("pTo", wintypes.LPCWSTR),
            ("fFlags", ctypes.c_uint16),
            ("fAnyOperationsAborted", wintypes.BOOL),
            ("hNameMappings", ctypes.c_void_p),
            ("lpszProgressTitle", wintypes.LPCWSTR),
        ]

    op = SHFILEOPSTRUCTW()
    op.wFunc = _FO_DELETE
    op.pFrom = path + "\0\0"  # double-null terminated list
    op.fFlags = _FOF_ALLOWUNDO | _FOF_NOCONFIRMATION | _FOF_SILENT | _FOF_NOERRORUI
    try:
        rc = ctypes.windll.shell32.SHFileOperationW(ctypes.byref(op))
    except Exception:  # noqa: BLE001
        return False
    return rc == 0 and not op.fAnyOperationsAborted


def _delete_entry(path: str, *, to_recycle_bin: bool) -> bool:
    if to_recycle_bin:
        return _send_to_recycle_bin(path)
    try:
        if os.path.isdir(path) and not os.path.islink(path):
            shutil.rmtree(path, ignore_errors=True)
            return not os.path.exists(path)
        os.remove(path)
        return True
    except OSError:
        return False


def _empty_recycle_bin() -> tuple[int, bool]:
    """Empty the Recycle Bin (all drives). Returns (bytes_freed_estimate, ok)."""
    _, nbytes = _recycle_bin_info()
    try:
        # NULL path = all drives; flags: no confirmation/progress/sound.
        rc = ctypes.windll.shell32.SHEmptyRecycleBinW(None, None, 0x00000001 | 0x00000002 | 0x00000004)
    except Exception:  # noqa: BLE001
        return (0, False)
    return (nbytes, rc == 0)


def clean_junk(keys: list[str]) -> dict:
    """Delete the junk in the given category keys. Only whitelisted keys act;
    unknown keys are ignored. Per-category counts + a grand total are returned.
    'caution'-risk categories go to the Recycle Bin so they stay recoverable;
    'safe' ones are removed permanently (they are regenerated on demand)."""
    by_key = {c["key"]: c for c in _junk_categories()}
    wanted = [by_key[k] for k in (keys or []) if k in by_key]
    results = []
    total_freed = 0
    for c in wanted:
        freed = 0
        removed = 0
        errors = 0
        if c.get("special") == "recycle_bin":
            freed, ok = _empty_recycle_bin()
            removed = 1 if ok else 0
            errors = 0 if ok else 1
        else:
            to_bin = c.get("risk") == "caution"
            recurse = c.get("recurse", True)
            for root in _resolved_roots(c):  # confined to the profile, de-duped
                if not os.path.isdir(root):
                    continue
                try:
                    entries = list(os.scandir(root))
                except OSError:
                    continue
                cutoff = time.time() - (c.get("min_age_days", 0) * 86400) if c.get("min_age_days") else None
                for entry in entries:
                    try:
                        if not _matches(entry.name, c.get("patterns")):
                            continue
                        sz = 0
                        if entry.is_file(follow_symlinks=False):
                            if cutoff is not None and entry.stat(follow_symlinks=False).st_mtime > cutoff:
                                continue
                            sz = entry.stat(follow_symlinks=False).st_size
                        elif entry.is_dir(follow_symlinks=False):
                            if not recurse or _is_reparse(entry):
                                continue  # never delete through a junction; honor recurse=False
                            if cutoff is not None and (
                                entry.stat(follow_symlinks=False).st_mtime > cutoff
                                or _tree_has_recent(entry.path, cutoff)
                            ):
                                continue  # dir holds fresh files — leave it alone
                            _, sz, _ = _scan_dir(entry.path, min_age_days=0, recurse=True)
                        else:
                            continue  # reparse file / other — skip
                        if _delete_entry(entry.path, to_recycle_bin=to_bin):
                            removed += 1
                            freed += sz
                        else:
                            errors += 1  # locked / in use — skipped
                    except OSError:
                        errors += 1
        total_freed += freed
        results.append(
            {
                "key": c["key"],
                "label": c["label"],
                "removed": removed,
                "bytes_freed": freed,
                "human": _human(freed),
                "errors": errors,
            }
        )
    return {"ok": True, "cleaned": results, "total_freed": total_freed, "total_human": _human(total_freed)}


# ── Routes ────────────────────────────────────────────────────────────────────


@maintenance_bp.route("/api/maintenance/junk/scan")
def maintenance_junk_scan_route():
    """Read-only preview of removable junk (count + bytes per category)."""
    return jsonify(scan_junk())


@maintenance_bp.route("/api/maintenance/junk/clean", methods=["POST"])
def maintenance_junk_clean_route():
    """Delete the selected junk categories. Localhost-only (it deletes files);
    the body is ``{"keys": ["user_temp", ...]}`` — only whitelisted keys act."""
    remote = request.remote_addr or ""
    if remote not in ("127.0.0.1", "::1"):
        return jsonify({"ok": False, "error": "cleanup is localhost-only"}), 403
    data = request.get_json() or {}
    keys = data.get("keys")
    if not isinstance(keys, list) or not keys:
        return jsonify({"ok": False, "error": "Missing required field: keys (non-empty list)"}), 400
    return jsonify(clean_junk([str(k) for k in keys]))
