r"""
maintenance.py — PC maintenance utilities for WinDesktopMgr (Maintenance tab).

Tier 1: junk / temp cleanup. Scan is read-only and always runs first so the UI
can preview exactly what will be removed and how much space it frees; cleaning
only ever touches the whitelisted category roots below — the API takes category
KEYS, never caller-supplied paths, so there is no path-traversal surface.

Design choices (carried over from the drive-swap review):
  * Preview-first: `scan_junk()` reports count/bytes/samples per category with
    no side effects; `clean_junk(keys)` acts only on those keys.
  * Safe-by-default: only USER-SCOPE junk that needs no elevation is deleted
    here (temp, caches, crash dumps, WER, Recycle Bin — all regenerated by
    Windows/apps). SYSTEM-SCOPE junk (C:\Windows\Temp, Windows Update payloads)
    is deliberately NOT deleted by this process; the tab hands those off to
    Windows' own Disk Cleanup (cleanmgr), which elevates through Windows itself
    — so the app never runs an elevated file-deleter of its own.
  * Python-first: os.scandir / os.remove / shutil.rmtree, with a ctypes
    SHFileOperation for the Recycle-Bin option and SHQuery/EmptyRecycleBin for
    the bin itself. No PowerShell.
"""

from __future__ import annotations

import ctypes
import hashlib
import heapq
import os
import shutil
import threading
import time
from ctypes import wintypes

from flask import Blueprint, jsonify, request

from disk import _validate_analyze_path  # drive-rooted / no-UNC / exists guard

maintenance_bp = Blueprint("maintenance", __name__)

# Every scan here walks a lot of filesystem (a %TEMP% walk alone is 100k+ files),
# so scans run in a background thread and the UI polls — a request never blocks a
# worker thread for the whole walk. One registry entry per scan key gives each of
# them the same hardened behaviour: single-flight (one run at a time), a short
# result cache so re-opening the tab is instant, and a rollback if the thread
# cannot start. Keeping this in ONE place matters — the concurrency here is
# subtle enough that three hand-rolled copies would drift.
_SCAN_TTL_S = 90
_SCANS_MAX = 24  # registry ceiling — see _evict_stale()
_scans_lock = threading.Lock()
_scans: dict[str, dict] = {"junk": {"running": False, "result": None, "ts": 0.0}}
# Legacy aliases: the junk scan predates the registry and callers/tests reference
# these names — they must stay bound to the same objects the registry uses.
_scan_lock = _scans_lock
_scan_state: dict = _scans["junk"]


# ── Junk categories ───────────────────────────────────────────────────────────
# Each category resolves to one or more ROOT directories (env-expanded at call
# time). `min_age_days` skips very recent entries so we never fight an active
# installer's temp files. `recurse` walks subdirs. Everything here is user-scope
# and regenerated on demand, so `risk` is "safe" (permanent delete); the
# `to_recycle_bin` path exists for future higher-risk categories.


def _expand(path: str) -> str:
    return os.path.expandvars(path)


def _junk_categories() -> list[dict]:
    """Return the junk categories with their roots resolved for this user.

    Kept as a function (not a module constant) so it re-reads env vars and so
    tests can monkeypatch env / the roots cleanly.
    """
    local = _expand(r"%LOCALAPPDATA%")
    return [
        {
            "key": "user_temp",
            "label": "Temporary files (your account)",
            "description": "Files left in your %TEMP% folder by installers and apps. Windows recreates it as needed.",
            "roots": [_expand(r"%TEMP%"), _expand(r"%TMP%")],
            "min_age_days": 1,  # leave today's temp alone (may be in use)
            "recurse": True,
            "risk": "safe",
        },
        {
            "key": "thumbnail_cache",
            "label": "Thumbnail & icon cache",
            "description": "Explorer's cached thumbnails/icons. Rebuilt automatically the next time you browse folders.",
            "roots": [os.path.join(local, r"Microsoft\Windows\Explorer")],
            "patterns": ("thumbcache_", "iconcache_"),
            "min_age_days": 0,
            "recurse": False,
            "risk": "safe",
        },
        {
            "key": "crash_dumps",
            "label": "Crash dumps",
            "description": "Application crash dumps in your profile. Only useful for debugging a specific crash.",
            "roots": [os.path.join(local, "CrashDumps")],
            "min_age_days": 0,
            "recurse": True,
            "risk": "safe",
        },
        {
            "key": "wer",
            "label": "Windows Error Reporting queue",
            "description": "Queued/archived error reports in your profile. Safe to clear.",
            "roots": [
                os.path.join(local, r"Microsoft\Windows\WER\ReportQueue"),
                os.path.join(local, r"Microsoft\Windows\WER\ReportArchive"),
            ],
            "min_age_days": 0,
            "recurse": True,
            "risk": "safe",
        },
        {
            "key": "recycle_bin",
            "label": "Recycle Bin",
            "description": "Everything currently in the Recycle Bin, for all drives. This is permanent — off by default.",
            "special": "recycle_bin",
            "risk": "safe",
            "default_off": True,  # emptying the bin is irreversible; don't pre-check it
        },
    ]


# ── Scanning (read-only) ──────────────────────────────────────────────────────


def _matches(name: str, patterns: tuple[str, ...] | None) -> bool:
    if not patterns:
        return True
    low = name.lower()
    return any(low.startswith(p.lower()) for p in patterns)


def _is_reparse(entry: os.DirEntry) -> bool:
    """True if a DirEntry is a symlink OR a junction/mount-point (reparse point).

    os.path.islink is False for directory junctions, so we check both — we never
    traverse INTO or delete THROUGH a reparse point (a junction planted in %TEMP%
    pointing at Documents must never be followed)."""
    try:
        if entry.is_symlink():
            return True
        is_junction = getattr(entry, "is_junction", None)
        if callable(is_junction) and is_junction():
            return True
    except OSError:
        return True  # can't tell -> treat as reparse; do not follow/delete
    return False


def _tree_has_recent(path: str, cutoff: float) -> bool:
    """True if any file under ``path`` has mtime newer than ``cutoff``.

    Lets a min-age category skip a whole directory that was created long ago but
    still holds fresh files (an active installer's temp dir): writing to an
    existing file does NOT bump the parent dir's mtime, so a top-level age check
    alone would delete live data. Short-circuits; never follows reparse points."""
    try:
        for entry in os.scandir(path):
            try:
                if entry.is_file(follow_symlinks=False):
                    if entry.stat(follow_symlinks=False).st_mtime > cutoff:
                        return True
                elif (
                    entry.is_dir(follow_symlinks=False)
                    and not _is_reparse(entry)
                    and _tree_has_recent(entry.path, cutoff)
                ):
                    return True
            except OSError:
                continue
    except OSError:
        return False
    return False


def _within_profile(root: str) -> bool:
    """Defence-in-depth: a cleanup root must be an absolute path UNDER the user
    profile. Rejects a drive root or a relative path from a misconfigured env
    var (e.g. %TEMP%=C:\\, or an empty %LOCALAPPDATA% yielding a relative root),
    so cleanup can never iterate the drive root or somewhere outside the profile.
    Every Tier-1 category lives under %USERPROFILE%."""
    if not root or not os.path.isabs(root):
        return False
    prof = os.path.expandvars("%USERPROFILE%")
    if not prof or not os.path.isabs(prof):
        return False
    n = os.path.normcase(os.path.normpath(root))
    if len(n.rstrip("\\/")) <= 2:  # drive root like "C:"
        return False
    p = os.path.normcase(os.path.normpath(prof))
    return n == p or n.startswith(p + os.sep)


def _resolved_roots(cat: dict) -> list[str]:
    """Category roots, de-duplicated (case-insensitive) and confined to the
    profile. %TEMP% and %TMP% usually resolve to the same dir; without de-dup the
    scan preview would double-count."""
    seen: set[str] = set()
    out: list[str] = []
    for root in cat.get("roots", []):
        if not _within_profile(root):
            continue
        key = os.path.normcase(os.path.normpath(root))
        if key in seen:
            continue
        seen.add(key)
        out.append(root)
    return out


def _scan_dir(root: str, *, min_age_days: int = 0, recurse: bool = True, patterns=None) -> tuple[int, int, list[str]]:
    """Return (file_count, total_bytes, sample_paths) under ``root``.

    Read-only. Silently skips entries it can't stat (locked/permission) and never
    follows reparse points. Only counts top-level entries matching ``patterns``.
    ``min_age_days`` skips entries modified within that window; for a directory it
    also skips the whole tree if it holds any file newer than the cutoff."""
    count = 0
    total = 0
    samples: list[str] = []
    cutoff = time.time() - (min_age_days * 86400) if min_age_days else None
    if not root or not os.path.isdir(root):
        return (0, 0, [])
    try:
        entries = list(os.scandir(root))
    except OSError:
        return (0, 0, [])
    for entry in entries:
        try:
            if not _matches(entry.name, patterns):
                continue
            if entry.is_file(follow_symlinks=False):
                if cutoff is not None and entry.stat(follow_symlinks=False).st_mtime > cutoff:
                    continue
                count += 1
                total += entry.stat(follow_symlinks=False).st_size
            elif entry.is_dir(follow_symlinks=False) and recurse:
                if _is_reparse(entry):
                    continue  # never traverse a junction/symlink
                if cutoff is not None and (
                    entry.stat(follow_symlinks=False).st_mtime > cutoff or _tree_has_recent(entry.path, cutoff)
                ):
                    continue  # dir holds fresh files — leave it alone
                c, b, _ = _scan_dir(entry.path, min_age_days=0, recurse=True, patterns=None)
                count += c + 1
                total += b
            else:
                continue
            if len(samples) < 5:
                samples.append(entry.path)
        except OSError:
            continue
    return (count, total, samples)


def _recycle_bin_info() -> tuple[int, int]:
    """(item_count, total_bytes) across all drives via SHQueryRecycleBinW."""

    class SHQUERYRBINFO(ctypes.Structure):
        _fields_ = [("cbSize", wintypes.DWORD), ("i64Size", ctypes.c_int64), ("i64NumItems", ctypes.c_int64)]

    info = SHQUERYRBINFO()
    info.cbSize = ctypes.sizeof(info)
    try:
        # NULL path = all drives. S_OK == 0.
        rc = ctypes.windll.shell32.SHQueryRecycleBinW(None, ctypes.byref(info))
    except Exception:  # noqa: BLE001 -- shell32 unavailable / non-Windows
        return (0, 0)
    if rc != 0:
        return (0, 0)
    return (int(info.i64NumItems), int(info.i64Size))


def _human(nbytes: int) -> str:
    n = float(nbytes)
    for unit in ("B", "KB", "MB", "GB", "TB"):
        if n < 1024 or unit == "TB":
            return f"{n:.0f} {unit}" if unit == "B" else f"{n:.1f} {unit}"
        n /= 1024
    return f"{nbytes} B"


def scan_junk() -> dict:
    """Read-only preview of removable junk. Never deletes anything."""
    cats = []
    total = 0
    for c in _junk_categories():
        if c.get("special") == "recycle_bin":
            count, nbytes = _recycle_bin_info()
            samples: list[str] = []
        else:
            count = 0
            nbytes = 0
            samples = []
            for root in _resolved_roots(c):
                rc, rb, rs = _scan_dir(
                    root,
                    min_age_days=c.get("min_age_days", 0),
                    recurse=c.get("recurse", True),
                    patterns=c.get("patterns"),
                )
                count += rc
                nbytes += rb
                samples.extend(rs)
        total += nbytes
        cats.append(
            {
                "key": c["key"],
                "label": c["label"],
                "description": c["description"],
                "risk": c.get("risk", "safe"),
                "default_off": bool(c.get("default_off")),
                "count": count,
                "bytes": nbytes,
                "human": _human(nbytes),
                "samples": samples[:5],
            }
        )
    return {"ok": True, "categories": cats, "total_bytes": total, "total_human": _human(total)}


def _slot(key: str) -> dict:
    """Return the registry entry for ``key`` (created on first use).
    Callers must already hold ``_scans_lock``."""
    return _scans.setdefault(key, {"running": False, "result": None, "ts": 0.0})


def _evict_stale() -> None:
    """Keep the registry bounded. Scan keys embed user-supplied parameters (the
    folder being scanned), and the tray runs for weeks — without this, every
    distinct folder a user ever types would keep its full result set alive for
    the life of the process. Oldest completed scans go first; a running scan is
    never evicted (its worker still needs the slot) and neither is the junk
    scan, which the tab reads on every open. Caller holds ``_scans_lock``."""
    if len(_scans) <= _SCANS_MAX:
        return
    evictable = sorted((st["ts"], k) for k, st in _scans.items() if k != "junk" and not st["running"])
    for _, key in evictable[: len(_scans) - _SCANS_MAX]:
        _scans.pop(key, None)


def _scan_worker(key: str, fn) -> None:
    """Background worker: run ``fn`` and cache its result under ``key``."""
    try:
        result = fn()
    except Exception as e:  # noqa: BLE001 -- a scan failure must not wedge the tab
        result = {"ok": False, "error": str(e)}
    with _scans_lock:
        st = _slot(key)
        st["result"] = result
        st["ts"] = time.time()
        st["running"] = False


def start_or_get(key: str, fn, *, force: bool = False, ttl: int = _SCAN_TTL_S) -> dict:
    """Non-blocking scan accessor. Returns ``{status: 'running'}`` while a scan
    is in flight, ``{status: 'done', **result}`` when a fresh result is cached,
    and kicks off a background scan (single-flight) otherwise. ``force`` starts a
    fresh scan even if a cached one is still warm.

    ``key`` namespaces the cache, so parametrised scans (different roots) must
    fold their parameters into it or they would serve each other's results."""
    with _scans_lock:
        st = _slot(key)
        _evict_stale()
        if st["running"]:
            return {"ok": True, "status": "running"}
        cached = st["result"]
        # Only a *successful* result is worth caching for the full TTL; a failed
        # scan (transient I/O error) should be retried on the next poll, not
        # served stale.
        fresh = cached is not None and cached.get("ok") is True and (time.time() - st["ts"]) < ttl
        if fresh and not force:
            return {"ok": True, "status": "done", **cached}
        st["running"] = True
    try:
        threading.Thread(target=_scan_worker, args=(key, fn), daemon=True, name=f"Scan-{key}").start()
    except Exception as e:  # noqa: BLE001 -- thread exhaustion must not wedge the tab
        with _scans_lock:
            _slot(key)["running"] = False
        return {"ok": False, "status": "error", "error": f"Could not start scan: {e}"}
    return {"ok": True, "status": "running"}


def _run_scan() -> None:
    """Background worker for the junk scan (thin wrapper over _scan_worker)."""
    _scan_worker("junk", scan_junk)


def start_or_get_scan(*, force: bool = False) -> dict:
    """Non-blocking accessor for the junk scan."""
    return start_or_get("junk", scan_junk, force=force)


# ── Space analysis (Tier 2 — READ ONLY) ───────────────────────────────────────
# Answers "what is actually eating my disk?". Deliberately analysis-only: it
# reports, it never deletes. Junk cleanup above is safe to automate because the
# categories are a fixed whitelist of regenerated files; the biggest file on your
# disk is just as likely to be a VM image or a video you care about, so choosing
# what goes is the user's call (Explorer is one click away via the Disk tab).
#
# Folder drill-down and the WinSxS component store are NOT re-implemented here —
# disk.py already has analyze_disk_path() and _get_winsxs_actual_size(), surfaced
# by the Disk tab's "Analyze Space" modal and Quick Wins.

_BIGFILE_MIN_BYTES = 50 * 1024 * 1024  # a "big file" worth reporting
_DUPE_MIN_BYTES = 1024 * 1024  # ignore small files — dedup noise, little payoff
_DUPE_MAX_GROUPS = 100
_PARTIAL_HASH_BYTES = 65536
_HASH_CHUNK = 1024 * 1024
# A duplicate hunt reads file CONTENT, so it needs a firm ceiling of its own.
_DUPE_HASH_BUDGET_BYTES = 8 * 1024**3
# Enumeration ceilings. A scan of C:\ would otherwise run for many minutes; a
# truncated-but-honest answer beats an unbounded one, and the UI says so.
_SPACE_MAX_FILES = 500_000
_SPACE_TIME_BUDGET_S = 150  # inside the frontend's ~3 min poll window
_CLOCK_EVERY = 200  # re-check the deadline every N files inside one directory


def _clamp_top_n(value) -> int:
    return max(5, min(int(value or 40), 200))


def _clamp_min_bytes(value) -> int:
    return max(4096, int(value or _DUPE_MIN_BYTES))


def _new_budget(max_files: int = _SPACE_MAX_FILES, seconds: int = _SPACE_TIME_BUDGET_S) -> dict:
    return {
        "files": 0,
        "max_files": max_files,
        "deadline": time.monotonic() + seconds,
        "truncated": False,
    }


def _over_budget(budget: dict) -> bool:
    return budget["files"] >= budget["max_files"] or time.monotonic() > budget["deadline"]


def _walk_files(root: str, budget: dict):
    """Yield ``(path, size)`` for every regular file under ``root``.

    Iterative (an explicit stack — no recursion limit on deep trees), never
    follows reparse points (a junction must not make the walk escape the root or
    loop), and skips directories/files it cannot read. Stops when the budget is
    spent, setting ``budget["truncated"]``."""
    stack = [root]
    while stack:
        if _over_budget(budget):
            budget["truncated"] = True
            return
        cur = stack.pop()
        try:
            with os.scandir(cur) as it:
                for entry in it:
                    try:
                        if _is_reparse(entry):
                            continue
                        if entry.is_dir(follow_symlinks=False):
                            stack.append(entry.path)
                            continue
                        if not entry.is_file(follow_symlinks=False):
                            continue
                        size = entry.stat(follow_symlinks=False).st_size
                    except OSError:
                        continue  # vanished / locked / denied — skip the entry
                    budget["files"] += 1
                    yield entry.path, size
                    # Enforce mid-directory: one folder can hold 100k files, so
                    # checking only between directories would sail past the cap.
                    # The count is a cheap int compare so it runs every file; the
                    # clock is a syscall, so it runs every _CLOCK_EVERY files.
                    # That interval is deliberately small: on a spun-down or
                    # network drive a single stat() can cost ~100ms, so checking
                    # only every few thousand files would overshoot the time
                    # budget by minutes and outlive the UI's poll window.
                    if budget["files"] >= budget["max_files"] or (
                        budget["files"] % _CLOCK_EVERY == 0 and time.monotonic() > budget["deadline"]
                    ):
                        budget["truncated"] = True
                        return
        except OSError:
            continue  # unreadable directory — skip the subtree


def _file_row(path: str, size: int) -> dict:
    return {
        "path": path,
        "name": os.path.basename(path),
        "dir": os.path.dirname(path),
        "bytes": size,
        "human": _human(size),
    }


def scan_large_files(root: str, top_n: int = 40) -> dict:
    """Top ``top_n`` largest individual files under ``root`` (read-only).

    A bounded min-heap keeps memory flat regardless of how many files are walked
    — only the current top N is ever held."""
    ok, cleaned = _validate_analyze_path(root)
    if not ok:
        return {"ok": False, "error": cleaned, "files": []}
    top_n = _clamp_top_n(top_n)
    budget = _new_budget()
    heap: list[tuple[int, str]] = []
    for path, size in _walk_files(cleaned, budget):
        if size < _BIGFILE_MIN_BYTES:
            continue
        if len(heap) < top_n:
            heapq.heappush(heap, (size, path))
        elif size > heap[0][0]:
            heapq.heapreplace(heap, (size, path))
    ranked = sorted(heap, key=lambda t: t[0], reverse=True)
    total = sum(size for size, _ in ranked)
    return {
        "ok": True,
        "root": cleaned,
        "scanned": budget["files"],
        "truncated": budget["truncated"],
        "min_bytes": _BIGFILE_MIN_BYTES,
        "min_human": _human(_BIGFILE_MIN_BYTES),
        "total_bytes": total,
        "total_human": _human(total),
        "files": [_file_row(p, s) for s, p in ranked],
    }


def _hash_file(path: str, limit: int | None = None) -> str:
    """SHA-256 of a file, or of its first ``limit`` bytes. ``""`` if unreadable."""
    h = hashlib.sha256()
    remaining = limit
    try:
        with open(path, "rb") as f:
            while True:
                want = _HASH_CHUNK if remaining is None else min(_HASH_CHUNK, remaining)
                if want <= 0:
                    break
                chunk = f.read(want)
                if not chunk:
                    break
                h.update(chunk)
                if remaining is not None:
                    remaining -= len(chunk)
    except OSError:
        return ""
    return h.hexdigest()


def find_duplicates(root: str, min_bytes: int = _DUPE_MIN_BYTES, max_groups: int = _DUPE_MAX_GROUPS) -> dict:
    """Find byte-identical files under ``root`` (read-only — reports only).

    Three passes, cheapest first, so almost no file is read in full:
      1. group by exact size — files of different sizes cannot be duplicates;
      2. hash the first 64 KB of each same-size candidate — same-size-but-
         different files (media especially) diverge early and drop out here;
      3. full SHA-256 only for files that survive, to confirm.
    Size alone is never treated as proof."""
    ok, cleaned = _validate_analyze_path(root)
    if not ok:
        return {"ok": False, "error": cleaned, "groups": []}
    min_bytes = _clamp_min_bytes(min_bytes)
    max_groups = max(5, min(int(max_groups or _DUPE_MAX_GROUPS), 500))
    budget = _new_budget()
    by_size: dict[int, list[str]] = {}
    for path, size in _walk_files(cleaned, budget):
        if size < min_bytes:
            continue
        by_size.setdefault(size, []).append(path)

    hashed_bytes = 0
    groups: list[dict] = []
    # Biggest sizes first: if the hash budget runs out, what we did spend it on is
    # the duplicates that waste the most space.
    for size in sorted((s for s, paths in by_size.items() if len(paths) > 1), reverse=True):
        if _over_budget(budget) or hashed_bytes >= _DUPE_HASH_BUDGET_BYTES:
            budget["truncated"] = True
            break
        candidates = by_size[size]
        partial: dict[str, list[str]] = {}
        for p in candidates:
            digest = _hash_file(p, limit=_PARTIAL_HASH_BYTES)
            hashed_bytes += min(size, _PARTIAL_HASH_BYTES)
            if digest:
                partial.setdefault(digest, []).append(p)
        for same_head in partial.values():
            if len(same_head) < 2:
                continue
            if size <= _PARTIAL_HASH_BYTES:
                # The "partial" hash already covered the whole file.
                confirmed: dict[str, list[str]] = {"whole": same_head}
            else:
                confirmed = {}
                for p in same_head:
                    digest = _hash_file(p)
                    hashed_bytes += size
                    if digest:
                        confirmed.setdefault(digest, []).append(p)
            for dupes in confirmed.values():
                if len(dupes) < 2:
                    continue
                wasted = size * (len(dupes) - 1)
                groups.append(
                    {
                        "bytes": size,
                        "human": _human(size),
                        "count": len(dupes),
                        "wasted_bytes": wasted,
                        "wasted_human": _human(wasted),
                        "files": [_file_row(p, size) for p in sorted(dupes)],
                    }
                )

    groups.sort(key=lambda g: g["wasted_bytes"], reverse=True)
    total_wasted = sum(g["wasted_bytes"] for g in groups)
    return {
        "ok": True,
        "root": cleaned,
        "scanned": budget["files"],
        "truncated": budget["truncated"],
        "min_bytes": min_bytes,
        "min_human": _human(min_bytes),
        "group_count": len(groups),
        "shown": min(len(groups), max_groups),
        "total_wasted_bytes": total_wasted,
        "total_wasted_human": _human(total_wasted),
        "groups": groups[:max_groups],
    }


def default_scan_root() -> str:
    """Where a space scan starts if the caller doesn't say: the user profile."""
    return os.path.expandvars("%USERPROFILE%")


# ── Cleaning ──────────────────────────────────────────────────────────────────

_FO_DELETE = 0x0003
_FOF_ALLOWUNDO = 0x0040
_FOF_NOCONFIRMATION = 0x0010
_FOF_SILENT = 0x0004
_FOF_NOERRORUI = 0x0400


def _send_to_recycle_bin(path: str) -> bool:
    """Delete ``path`` to the Recycle Bin via SHFileOperationW. Returns success."""

    class SHFILEOPSTRUCTW(ctypes.Structure):
        _fields_ = [
            ("hwnd", wintypes.HWND),
            ("wFunc", wintypes.UINT),
            ("pFrom", wintypes.LPCWSTR),
            ("pTo", wintypes.LPCWSTR),
            ("fFlags", ctypes.c_uint16),
            ("fAnyOperationsAborted", wintypes.BOOL),
            ("hNameMappings", ctypes.c_void_p),
            ("lpszProgressTitle", wintypes.LPCWSTR),
        ]

    op = SHFILEOPSTRUCTW()
    op.wFunc = _FO_DELETE
    op.pFrom = path + "\0\0"  # double-null terminated list
    op.fFlags = _FOF_ALLOWUNDO | _FOF_NOCONFIRMATION | _FOF_SILENT | _FOF_NOERRORUI
    try:
        rc = ctypes.windll.shell32.SHFileOperationW(ctypes.byref(op))
    except Exception:  # noqa: BLE001
        return False
    return rc == 0 and not op.fAnyOperationsAborted


def _delete_entry(path: str, *, to_recycle_bin: bool) -> bool:
    if to_recycle_bin:
        return _send_to_recycle_bin(path)
    try:
        if os.path.isdir(path) and not os.path.islink(path):
            shutil.rmtree(path, ignore_errors=True)
            return not os.path.exists(path)
        os.remove(path)
        return True
    except OSError:
        return False


def _empty_recycle_bin() -> tuple[int, bool]:
    """Empty the Recycle Bin (all drives). Returns (bytes_freed_estimate, ok)."""
    _, nbytes = _recycle_bin_info()
    try:
        # NULL path = all drives; flags: no confirmation/progress/sound.
        rc = ctypes.windll.shell32.SHEmptyRecycleBinW(None, None, 0x00000001 | 0x00000002 | 0x00000004)
    except Exception:  # noqa: BLE001
        return (0, False)
    return (nbytes, rc == 0)


def clean_junk(keys: list[str]) -> dict:
    """Delete the junk in the given category keys. Only whitelisted keys act;
    unknown keys are ignored. Per-category counts + a grand total are returned.
    'caution'-risk categories go to the Recycle Bin so they stay recoverable;
    'safe' ones are removed permanently (they are regenerated on demand)."""
    by_key = {c["key"]: c for c in _junk_categories()}
    wanted = [by_key[k] for k in (keys or []) if k in by_key]
    results = []
    total_freed = 0
    for c in wanted:
        freed = 0
        removed = 0
        errors = 0
        if c.get("special") == "recycle_bin":
            freed, ok = _empty_recycle_bin()
            removed = 1 if ok else 0
            errors = 0 if ok else 1
        else:
            to_bin = c.get("risk") == "caution"
            recurse = c.get("recurse", True)
            for root in _resolved_roots(c):  # confined to the profile, de-duped
                if not os.path.isdir(root):
                    continue
                try:
                    entries = list(os.scandir(root))
                except OSError:
                    continue
                cutoff = time.time() - (c.get("min_age_days", 0) * 86400) if c.get("min_age_days") else None
                for entry in entries:
                    try:
                        if not _matches(entry.name, c.get("patterns")):
                            continue
                        sz = 0
                        if entry.is_file(follow_symlinks=False):
                            if cutoff is not None and entry.stat(follow_symlinks=False).st_mtime > cutoff:
                                continue
                            sz = entry.stat(follow_symlinks=False).st_size
                        elif entry.is_dir(follow_symlinks=False):
                            if not recurse or _is_reparse(entry):
                                continue  # never delete through a junction; honor recurse=False
                            if cutoff is not None and (
                                entry.stat(follow_symlinks=False).st_mtime > cutoff
                                or _tree_has_recent(entry.path, cutoff)
                            ):
                                continue  # dir holds fresh files — leave it alone
                            _, sz, _ = _scan_dir(entry.path, min_age_days=0, recurse=True)
                        else:
                            continue  # reparse file / other — skip
                        if _delete_entry(entry.path, to_recycle_bin=to_bin):
                            removed += 1
                            freed += sz
                        else:
                            errors += 1  # locked / in use — skipped
                    except OSError:
                        errors += 1
        total_freed += freed
        results.append(
            {
                "key": c["key"],
                "label": c["label"],
                "removed": removed,
                "bytes_freed": freed,
                "human": _human(freed),
                "errors": errors,
            }
        )
    return {"ok": True, "cleaned": results, "total_freed": total_freed, "total_human": _human(total_freed)}


# ── Routes ────────────────────────────────────────────────────────────────────


@maintenance_bp.route("/api/maintenance/junk/scan")
def maintenance_junk_scan_route():
    """Read-only preview of removable junk (count + bytes per category).

    Non-blocking: a full %TEMP% walk can take ~a minute, so this returns
    ``status: 'running'`` and runs the scan in a background thread; the client
    polls until ``status: 'done'``. ``?refresh=1`` forces a fresh scan."""
    force = request.args.get("refresh") in ("1", "true", "yes")
    return jsonify(start_or_get_scan(force=force))


@maintenance_bp.route("/api/maintenance/junk/clean", methods=["POST"])
def maintenance_junk_clean_route():
    """Delete the selected junk categories. Localhost-only (it deletes files);
    the body is ``{"keys": ["user_temp", ...]}`` — only whitelisted keys act."""
    remote = request.remote_addr or ""
    if remote not in ("127.0.0.1", "::1"):
        return jsonify({"ok": False, "error": "cleanup is localhost-only"}), 403
    data = request.get_json() or {}
    keys = data.get("keys")
    if not isinstance(keys, list) or not keys:
        return jsonify({"ok": False, "error": "Missing required field: keys (non-empty list)"}), 400
    return jsonify(clean_junk([str(k) for k in keys]))


def _space_root() -> str:
    """Resolve the ``?root=`` query arg, defaulting to the user profile."""
    return (request.args.get("root") or "").strip() or default_scan_root()


def _cache_root(cleaned: str) -> str:
    """Canonical form of a validated root, for use in a cache key.

    ``C:\\Users\\Bob``, ``C:\\Users\\Bob\\`` and ``C:/Users/Bob`` are the same
    folder; without normalising, each spelling would mint its own permanent
    registry entry."""
    return os.path.normcase(os.path.normpath(cleaned))


@maintenance_bp.route("/api/maintenance/space/large-files")
def maintenance_large_files_route():
    """Top-N largest individual files under ``?root=`` (default: user profile).

    Read-only. Non-blocking (background thread + poll), same as the junk scan."""
    ok, cleaned = _validate_analyze_path(_space_root())
    if not ok:
        return jsonify({"ok": False, "status": "error", "error": cleaned, "files": []}), 422
    top_n = _clamp_top_n(request.args.get("top_n", type=int))
    force = request.args.get("refresh") in ("1", "true", "yes")
    # Key off the VALIDATED, CLAMPED values. Keying off the raw query args would
    # let top_n=201 / 5000 / 999999 — all identical after clamping — each mint a
    # separate permanent registry entry.
    key = f"large_files:{_cache_root(cleaned)}:{top_n}"
    return jsonify(start_or_get(key, lambda: scan_large_files(cleaned, top_n), force=force))


@maintenance_bp.route("/api/maintenance/space/duplicates")
def maintenance_duplicates_route():
    """Byte-identical duplicate files under ``?root=`` (default: user profile).

    Read-only: it reports groups, it never deletes. Non-blocking."""
    ok, cleaned = _validate_analyze_path(_space_root())
    if not ok:
        return jsonify({"ok": False, "status": "error", "error": cleaned, "groups": []}), 422
    min_bytes = _clamp_min_bytes(request.args.get("min_bytes", type=int))
    force = request.args.get("refresh") in ("1", "true", "yes")
    key = f"duplicates:{_cache_root(cleaned)}:{min_bytes}"
    return jsonify(start_or_get(key, lambda: find_duplicates(cleaned, min_bytes), force=force))
