"""Write requirements.lock: the exact installed version of every package in
requirements.txt and everything those packages pull in (tech-debt #66).

requirements.txt says what the app needs ("flask>=3.0"); the lock says what
it was last tested with ("flask==3.1.3"). Reinstalling from the lock on a
new drive gives the same versions that passed the test suite.

Regenerate after any dependency change (it reads THIS Python's installed
packages, so run it from the environment the tests pass in):

    python scripts/lock_requirements.py

Reinstall:

    pip install -r requirements.lock
"""

from __future__ import annotations

import sys
from collections.abc import Callable
from importlib.metadata import PackageNotFoundError, distribution
from pathlib import Path

from packaging.requirements import Requirement
from packaging.utils import canonicalize_name

ROOT = Path(__file__).resolve().parent.parent
LOCK_FILE = ROOT / "requirements.lock"


def read_requirements(path: Path) -> list[str]:
    """Requirement lines of a requirements file: no comments, blanks or -r includes."""
    out: list[str] = []
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.split("#", 1)[0].strip()
        if line and not line.startswith("-"):
            out.append(line)
    return out


def requirement_name(spec: str) -> str:
    return Requirement(spec).name


def _installed(name: str) -> tuple[str, list[str]]:
    dist = distribution(name)
    return dist.version, list(dist.requires or [])


def resolve(specs: list[str], lookup: Callable[[str], tuple[str, list[str]]] = _installed) -> dict[str, str]:
    """{canonical name: installed version} for ``specs`` and everything they
    require on this platform. Optional extras are left out."""
    pins: dict[str, str] = {}
    queue = list(specs)
    while queue:
        req = Requirement(queue.pop())
        if req.marker is not None and not req.marker.evaluate({"extra": ""}):
            continue
        key = canonicalize_name(req.name)
        if key in pins:
            continue
        try:
            version, requires = lookup(req.name)
        except PackageNotFoundError:
            raise SystemExit(f"not installed: {req.name} -- pip install -r requirements.txt first") from None
        # A lock must never contradict requirements.txt (e.g. anthropic<1).
        if req.specifier and not req.specifier.contains(version, prereleases=True):
            raise SystemExit(f"{req.name} {version} is installed but requirements allow {req.name}{req.specifier}")
        pins[key] = version
        queue.extend(requires)
    return dict(sorted(pins.items()))


def render(pins: dict[str, str]) -> str:
    header = (
        "# Exact versions the test suite last passed with. Generated by\n"
        "# scripts/lock_requirements.py from requirements.txt -- do not edit by hand.\n"
        "# Reinstall: pip install -r requirements.lock\n"
    )
    return header + "".join(f"{name}=={version}\n" for name, version in pins.items())


def main() -> int:
    pins = resolve(read_requirements(ROOT / "requirements.txt"))
    LOCK_FILE.write_text(render(pins), encoding="utf-8", newline="\n")
    print(f"wrote {LOCK_FILE.name}: {len(pins)} packages")
    return 0


if __name__ == "__main__":
    sys.exit(main())
